/**
 * A validation result code identifier.
 *
 * Codes can be strings or numbers and may be resolved through a result catalog.
 */
export type ResultCode = string | number;

/**
 * A map of localized messages keyed by language code.
 *
 * Use `default` when a message should be used as a fallback for unspecified languages.
 */
export type TranslationMap = Record<string, string>;

/**
 * Defines optional messages for a validation code.
 *
 * Each level can be either a single message string or a localized translation map.
 */
export interface ResultCodeDefinition {

    /** Informational guidance that does not indicate a failure. */
    hint?: string | TranslationMap;

    /** A non-fatal warning message. */
    warn?: string | TranslationMap;

    /** An error message that marks the result as invalid. */
    err?: string | TranslationMap;
}

/**
 * Resolves result code definitions and localized messages.
 */
export interface IResultCatalog {

    /**
     * Returns a resolved result object for a code in the requested language.
     */
    getResult(code: ResultCode, lang?: string): SingleResult | undefined;

    /**
     * Returns the raw definition stored for a code.
     */
    getDefinition(code: ResultCode): ResultCodeDefinition | undefined;

    /**
     * Lists all registered codes.
     */
    listCodes(): ResultCode[];
}

/**
 * The base shape of a single validation result.
 */
export interface SingleResult {

    /** Indicates whether the result is valid. */
    valid: boolean;

    /** The field or index associated with the result, when applicable. */
    field?: string | number | null | undefined;

    /** Informational guidance generated by the check. */
    hint?: string | string[];

    /** Non-fatal warnings generated by the check. */
    warn?: string | string[];

    /** Validation errors generated by the check. */
    err?: string | string[];

    /** Optional machine-readable code associated with the result. */
    code?: ResultCode;
}

/**
 * A validation result that can aggregate child results and flattened messages.
 */
export interface ResultSet extends SingleResult {

    /** The original input value represented by this result set. */
    input?: any;

    /** Child results collected during nested validation. */
    results?: IResult[];

    /** Flattened hint messages collected from child results. */
    hints?: string[];

    /** Flattened warning messages collected from child results. */
    warnings?: string[];

    /** Flattened error messages collected from child results. */
    errors?: string[];
}

/**
 * A validation result, either a single item or an aggregate result set.
 */
export type IResult = SingleResult | ResultSet;

/**
 * Shared options used when appending a validation message.
 */
export interface CheckOptions {

    /** Custom hint message or messages to add when the check records a hint. */
    hint?: string | string[];

    /** Custom warning message or messages to add when the check records a warning. */
    warn?: string | string[];

    /** Custom error message or messages to add when the check records an error. */
    err?: string | string[];

    /** Optional code attached to the produced result. */
    code?: ResultCode;

    /** Catalog used to resolve result codes into localized messages. */
    catalog?: IResultCatalog;
}

/**
 * Options for array contains-style matching.
 */
export interface ArrayContainsOptions extends CheckOptions {

    /** Minimum number of array items that must satisfy the nested item checks. Defaults to 1. */
    minCount?: number;

    /** Maximum number of array items that may satisfy the nested item checks. */
    maxCount?: number;

    /** Optional custom error used when too few items match. */
    minErr?: string | string[];

    /** Optional custom error used when too many items match. */
    maxErr?: string | string[];
}

/**
 * Options for checks that can accept a more permissive input mode.
 */
export interface TolerantCheckOptions extends CheckOptions {

    /**
     * Allows coercion-friendly behavior where supported by the check.
     */
    tolerant?: boolean;
}

/**
 * Options specific to string-based checks.
 */
export interface StringCheckOptions extends CheckOptions {

    /** Controls case-sensitive versus case-insensitive matching. */
    case?: 'sensitive' | 'insensitive';
}

/**
 * Options for equality-style checks.
 */
export interface EqualityCheckOptions extends TolerantCheckOptions {

    /** Controls case-sensitive versus case-insensitive matching. */
    case?: 'sensitive' | 'insensitive';
}

/**
 * Controls how a check formats and returns its result.
 */
export interface ResultOptions {

    /** Preferred language for catalog-resolved messages. */
    language?: string;

    /** Catalog used to resolve result codes during result generation. */
    catalog?: IResultCatalog;

    /** Returns the original nested result structure without post-processing. */
    raw?: boolean;

    /** Returns results grouped by field where supported. */
    nested?: boolean;

    /** Returns the validated input value using either partial or strict pruning. */
    validated?: 'partial' | 'strict';

    /** Returns flattened top-level hint, warning, and error arrays. */
    flattened?: boolean;
}

/**
 * Common interface implemented by all check classes.
 */
export interface Check {

    /**
     * Builds the validation result for the current check.
     */
    result(options?: ResultOptions): IResult;
}